runtime: python39  # Use the appropriate Python runtime version

entrypoint: gunicorn -b :$5000 app.py:app  # Replace your_app_module with the actual module containing your Flask app

env_variables:
  FLASK_ENV: "production"

handlers:
- url: /.*
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
